module.exports = {
  'Akamai': 'akamai.com',
  '微软': 'microsoft.com',
  'Microsoft': 'microsoft.com',
  'j:COM电信': 'jcom.co.jp',
  'HANELCOM公司': 'hanelcom.vn',
  'Yandex': 'yandex.ru',
  'Zenlayer': 'zenlayer.com',
  'Facebook': 'facebook.com',
  'NTT网络': 'ntt.com',
  'NTT通信': 'ntt.com',
  'Cogent通信': 'cogentco.com',
  'DigitalOcean': 'digitalocean.com',
  'KT电信': 'kt.com',
  'Amazon数据中心': 'amazon.com',
  '亚马逊(Amazon)公司数据中心': 'amazon.com',
  'GoDaddy': 'godaddy.com',
  'StarHub': 'starhub.com',
  'OVH': 'ovh.com',
  'Google Fiber': 'fiber.google.com',
  'Google云计算': 'cloud.google.com',
  '国际航空电讯集团公司(SITA)': 'sita.aero',
  'True网络': 'trueinternet.co.th',
}
